# Generated by Django 4.2.30 on 2026-06-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
