# Generated by Django 6.0.6 on 2026-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactRequest',
        ),
    ]
