# Generated by Django 6.0.6 on 2026-07-01 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_contactrequest_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='party_size',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
